name: Run API Tests

on:
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t selenium-java-test .

      - name: Run tests inside Docker
        run: |
          docker run --rm --user root \
            -v ${{ github.workspace }}/allure-results:/app/target/allure-results \
            selenium-java-test mvn test

      - name: Generate Allure report inside Docker
        run: |
          docker run --rm --user root \
            -v ${{ github.workspace }}/allure-results:/app/target/allure-results \
            -v ${{ github.workspace }}/allure-report:/app/target/site/allure-maven-plugin \
            selenium-java-test mvn allure:report

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
