name: Run API Tests

on:
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t selenium-java-test .

      - name: Run tests and generate Allure report inside Docker
        run: |
          docker run --rm --user root \
            -v ${{ github.workspace }}/allure-results:/app/target/allure-results \
            -v ${{ github.workspace }}/allure-report:/app/target/site/allure-maven-plugin \
            selenium-java-test mvn clean test allure:report

      - name: Debug Docker report folder (optional)
        run: |
          ls -l ${{ github.workspace }}/allure-repo
